name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ng-app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ng-app

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
        working-directory: ng-app

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ng-app

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ng-app/playwright-report/
          retention-days: 30

  build-and-deploy:
    needs: playwright-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ng-app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ng-app

      - name: Build
        run: npm run build -- --configuration production --base-href /FilterLab/
        working-directory: ng-app

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ng-app/dist/filterLab-ng-app

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
